services:
  php-pure-php-x509:
    build: .
    container_name: php-pure-php-x509
    volumes:
      - ./certs:/etc/nginx/certs

  web-server:
    image: nginx:alpine
    container_name: web-server
    depends_on:
      php-pure-php-x509:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs
